services:
  mongodb:
    image: mongo:8
    container_name: pagemate-mongodb
    restart: unless-stopped
    env_file:
      - .env
    # Expose MongoDB on the host (default: 27017)
    ports:
      - "${MONGO_PORT:-27017}:27017"
    # Initialize root user and optional default database
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME:-pagemate}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD:-pagemate}"
      MONGO_INITDB_DATABASE: "${MONGO_INITDB_DATABASE:-pagemate}"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      # Use credentials to ping admin DB
      test: [
        "CMD-SHELL",
        "mongosh --quiet \"mongodb://${MONGO_INITDB_ROOT_USERNAME:-pagemate}:${MONGO_INITDB_ROOT_PASSWORD:-pagemate}@localhost:27017/admin\" --eval \"db.adminCommand('ping')\""
      ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  mongo_data:

networks:
  default:
    name: pagemate-net
