[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymongo>=4.6.1",
    "openai>=1.40.0",
    "dnspython>=2.4.0",
    "python-dotenv>=1.0.1",
    "dotenv>=0.9.9",
    "pypdf>=6.0.0",
]
